// Generated by Wrangler by running `wrangler types`

interface Env {
	SITE_URL: string;
	MAILTRAP_API_KEY: string;
	MAILTRAP_HOST: string;
	MAILTRAP_API_USER: string;
	MAILTRAP_PORT: string;
	MAILTRAP_FROM_EMAIL: string;
	MAILTRAP_TO_EMAIL: string;
	PAGESPEED_API_KEY: string;
	PAGESPEED_WEBHOOK_URL: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
}
