#:schema node_modules/wrangler/config-schema.json

name = "simongreer"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }

[observability]
enabled = true
