#:schema node_modules/wrangler/config-schema.json

main = "dist/_worker.js/index.js"
name = "simongreer"
type = "javascript"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]
mode = "smart"